name: Train Model and Generate CML Report

# This workflow runs on pushes to the main branch
on:
  push:
    branches: [ main ]

jobs:
  train-and-report:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository code
      - uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install all necessary Python libraries
      - name: Install dependencies
        run: |
          pip install pandas numpy mlflow scikit-learn matplotlib seaborn

      # Step 4: Run the main training script to log experiments to MLflow
      # The script connects to your remote MLflow server
      - name: Run training and poisoning experiments
        run: |
          python train.py

      # Step 5: Run the reporting script to fetch data and generate CML assets
      # This script will create report.md and accuracy_dashboard.png
      - name: Generate CML report assets
        run: |
          python create_report.py
      
      # Step 6: Use CML to post the report as a comment on the commit
      # The GITHUB_TOKEN is required for the action to have permission to comment
      - name: Create CML report
        uses: iterative/cml-action@v2
        with:
          # The content of the report is read from this markdown file
          report: report.md
        env:
          # This secret token is automatically provided by GitHub
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
